# Generated by Django 4.2.6 on 2023-10-29 20:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_number',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
