# Generated by Django 4.2.6 on 2023-10-29 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('users', '0002_alter_user_personal_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_courses',
            field=models.ManyToManyField(blank=True, related_name='students_current', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='passed_courses',
            field=models.ManyToManyField(blank=True, related_name='students_passed', to='courses.course'),
        ),
    ]
