# Generated by Django 4.2.6 on 2023-10-30 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_changepasswordtoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deputyeducational',
            options={'verbose_name': 'Deputy Educational', 'verbose_name_plural': 'Deputy Educationals'},
        ),
        migrations.AlterModelOptions(
            name='itmanager',
            options={'verbose_name': 'IT Manager', 'verbose_name_plural': 'IT Managers'},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professors'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='personnel_number',
            new_name='personal_number',
        ),
    ]
