# Generated by Django 4.2 on 2023-11-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('users', '0003_alter_student_current_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_courses',
            field=models.ManyToManyField(blank=True, related_name='students_current', to='courses.courseterm'),
        ),
    ]
