services:
  website:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      - "8000:80"
    depends_on:
      - db
      - redis

  db:
    container_name: postgres
    image: postgres:16
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  redis:
    container_name: redis
    image: redis:7.2

  minio:
    container_name: minio
    image: minio/minio:RELEASE.2023-11-15T20-43-25Z
    ports:
      - "9000:9000"
    environment:
      - "MINIO_ROOT_USER=minioadmin"
      - "MINIO_ROOT_PASSWORD=minioadmin"
    command: server /data
    volumes:
      - minio_data:/data

volumes:
  minio_data: