<<<<<<< HEAD
# Generated by Django 4.2.6 on 2023-10-29 18:39
=======
# Generated by Django 4.2.6 on 2023-10-29 20:01
>>>>>>> b541cb0eb1ab4b6c4bd351bdc3cfaa5dfa7d43d3

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
<<<<<<< HEAD
                ('course_unit', models.PositiveIntegerField()),
=======
                ('course_unit', models.PositiveIntegerField(default=1)),
>>>>>>> b541cb0eb1ab4b6c4bd351bdc3cfaa5dfa7d43d3
                ('course_type', models.CharField(choices=[('G', 'عمومی'), ('P', 'تخصصی')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CourseTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('class_day', models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('T', 'Thursday'), ('F', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=100)),
                ('class_time', models.TimeField()),
                ('exam_date_time', models.DateTimeField()),
                ('class_location', models.CharField(max_length=255)),
                ('exam_location', models.CharField(max_length=255)),
=======
                ('class_day', models.CharField(choices=[('Monday', 'دوشنبه'), ('Tuesday', 'سه\u200cشنبه'), ('Wednesday', 'چهارشنبه'), ('Thursday', 'پنج\u200cشنبه'), ('Friday', 'جمعه'), ('Saturday', 'شنبه'), ('Sunday', 'یک\u200cشنبه')], default='Saturday', max_length=100)),
                ('class_time', models.TimeField(default='12:00:00')),
                ('exam_date_time', models.DateTimeField()),
                ('class_location', models.CharField(blank=True, max_length=255, null=True)),
                ('exam_location', models.CharField(blank=True, max_length=255, null=True)),
>>>>>>> b541cb0eb1ab4b6c4bd351bdc3cfaa5dfa7d43d3
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('pass', 'قبول'), ('failed', 'مردود'), ('idk', 'مشروط')], max_length=255, null=True)),
                ('grade', models.FloatField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudyField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
<<<<<<< HEAD
                ('educations_groupe', models.CharField(max_length=255)),
=======
                ('educations_groupe', models.CharField(blank=True, max_length=255, null=True)),
>>>>>>> b541cb0eb1ab4b6c4bd351bdc3cfaa5dfa7d43d3
                ('total_units', models.PositiveIntegerField()),
                ('level', models.CharField(choices=[('کارشناسی', 'کارشناسی'), ('کارشناسی ارشد', 'کارشناسی ارشد'), ('PHD', 'PHD')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Mehr', 'مهر'), ('Bahman', 'بهمن'), ('Summer', 'تابستان')], max_length=255)),
                ('start_course_selection', models.DateField()),
                ('end_course_selection', models.DateField()),
                ('start_classes', models.DateField()),
                ('end_classes', models.DateField()),
                ('start_course_correction', models.DateField()),
                ('end_course_correction', models.DateField()),
                ('end_emergency_drop', models.DateField()),
                ('start_exams', models.DateField()),
                ('end_term', models.DateField()),
            ],
        ),
    ]
