# Generated by Django 4.2.6 on 2023-10-31 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='professors',
            field=models.ManyToManyField(to='users.professor'),
        ),
        migrations.AddField(
            model_name='term',
            name='students',
            field=models.ManyToManyField(to='users.student'),
        ),
        migrations.AddField(
            model_name='studyfield',
            name='faculty',
            field=models.ManyToManyField(to='courses.faculty'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='course_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.courseterm'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.student'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.term'),
        ),
        migrations.AddField(
            model_name='courseterm',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='courseterm',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.professor'),
        ),
        migrations.AddField(
            model_name='courseterm',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='courses.term'),
        ),
        migrations.AddField(
            model_name='course',
            name='co_requisites',
            field=models.ManyToManyField(blank=True, related_name='courses_concurrent', to='courses.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='faculty',
            field=models.ManyToManyField(to='courses.faculty'),
        ),
        migrations.AddField(
            model_name='course',
            name='pre_requisites',
            field=models.ManyToManyField(blank=True, related_name='courses_required', to='courses.course'),
        ),
    ]
