# Generated by Django 4.2.6 on 2023-10-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='co_requisites',
            field=models.ManyToManyField(blank=True, related_name='courses_concurrent', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_unit',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='pre_requisites',
            field=models.ManyToManyField(blank=True, related_name='courses_required', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='courseterm',
            name='class_day',
            field=models.CharField(choices=[('Monday', 'دوشنبه'), ('Tuesday', 'سه\u200cشنبه'), ('Wednesday', 'چهارشنبه'), ('Thursday', 'پنج\u200cشنبه'), ('Friday', 'جمعه'), ('Saturday', 'شنبه'), ('Sunday', 'یک\u200cشنبه')], default='Saturday', max_length=100),
        ),
        migrations.AlterField(
            model_name='courseterm',
            name='class_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='courseterm',
            name='class_time',
            field=models.TimeField(default='12:00:00'),
        ),
        migrations.AlterField(
            model_name='courseterm',
            name='exam_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studyfield',
            name='educations_groupe',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
