# Generated by Django 4.2 on 2023-11-01 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        ('users', '0003_alter_student_current_courses_and_more'),
        ('student_requests', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectionTemporaryRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_course', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_correction_courses', to='courses.courseterm')),
                ('remove_course', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='remove_correction_courses', to='courses.courseterm')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
    ]
