# Generated by Django 4.2 on 2023-11-01 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_student_current_courses'),
        ('student_requests', '0004_remove_correctiontemporaryrequests_add_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctiontemporaryrequests',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.student'),
        ),
    ]
